name: Continuous-integration-with-github

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Build your Docker image
      - name: Build front-end image
        run: docker build -t joaovbrocchi78/teste-frontend-app:latest ../../front-end/

      - name: Build back-end image
        run:  docker build -t joaovbrocchi78/teste-backend-app:latest ../../back-end/
  
      # Log in to Docker Hub
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the Docker image to Docker Hub
      - name: Push Docker front-end image
        run: docker push joaovbrocchi78/teste-frontend-app:latest
        
      - name: Push Docker back-end image
        run: docker push joaovbrocchi78/teste-backend-app:latest
